language: rust

matrix:
  fast_finish: true
  include:
    #- rust: nightly-x86_64-pc-windows-msvc
    #  os: windows
    - rust: nightly
      os: linux


before_script: |
  rustup component add rustfmt-preview
  rustup component add clippy-preview

script: |
  cargo check --all --benches --bins --examples --tests
  cargo fmt --all -- --check
  cargo clippy -- -D clippy::all
  cargo test --all  --verbose
  cargo build --verbose

cache: cargo

deploy:
  - provider: cargo
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = nightly && $TRAVIS_OS_NAME = linux"
      branch: master
    token:
      secure: Vx64IHlMd9lqIiWbCpw9nyqeSaYfZ6n08KGBjpKolQpmVyUTupWHVxiKzR12uaICxiC/Fy+YB2mRi4+UKvOUuVKgDXx/OQW5OmYV/ivPqL2DlUd8NEA85PN6VUE7nkK7ECH1Hs4hVcNcDVCRf+TT9TinODNIvKmLQR7rLYoSRK4HvIhw1eaSeBVuPMLC55KeJD5kY3THq83iT/1jUnebWncNiIDO8v2PXNsC2smS5igk6dPYo/AsXvCJRxveqrvdZFLxFrcBovEJ8NFpaCSG9sKYldR+Cm04/7aq8XFo5LN4SZtODFCBoxG9kN/03aVkUJROiHcP1YqD4t9kbHWrRX9hfqv4yqc1c1xbBNrrQp4NauBxbH07+8d6Z6C0oVx+XBZrzmC+c5NF3va4oSZijpmyW600w2BSAAKGd2i+IpdcNVXnRwerFFa2kAOut0a+EREu157hTPbfZXFv0HxYYbCfJRikN8aMApp5YQfCd8ifO+8/KH/Sv1WBePnwxmmRD4GudOx+h9/8HIKA0jw/qeyMcA7hx7HB+93hosd5pmV+aJijASjkNbpsX5ZY4Tp4oQRIubp0H+BKMO74BOt+SYdLXzbNeeLRp9KjhStc00DBI3INrDmhjIvgzHdjJYOQkgJR66dZQMdntFBYuwGrk6/xqGybi8hfP3mKEF/jx9Y=
