[package]
name = "igdb-client"
version = "0.0.1"
authors = ["Carlos Landeras"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.4"
surf = "1.0.1"
serde_derive = "1.0.99"
serde_json = "1.0.40"
serde = "1.0.99"
serde_repr = "0.1.5"
http = "0.1.18"
url = "2.1.0"
isahc = "0.7"

[dev-dependencies]
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly","compat"] }

[[example]]
name = "search-first-game-by-name"
path = "examples/search_first_game_by_name.rs"
[[example]]
name = "search-games-by-name"
path = "examples/search_games_by_name.rs"
[[example]]
name = "download-game-images"
path = "examples/download_game_images.rs"
[[example]]
name = "multiplayer-custom-query"
path = "examples/multiplayer_custom_query.rs"
[[example]]
name = "game-engine-info"
path = "examples/game_engine_info.rs"
[[example]]
name = "game-video-urls"
path = "examples/game_video_urls.rs"
[[example]]
name = "game-platforms"
path = "examples/game_platforms.rs"
[[example]]
name = "game-release-date"
path = "examples/game_release_date.rs"