[package]
name = "igdb-client"
version = "0.1.0"
authors = ["clanderas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.3"
surf = "1.0.1"
serde_derive = "1.0.99"
serde_json = "1.0.40"
serde = "1.0.99"
serde_repr = "0.1.5"
http = "0.1.18"
url = "2.1.0"

[dev-dependencies]
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly","compat"] }

[[example]]
name = "search-game-by_name"
path = "examples/search_game_by_name.rs"
[[example]]
name = "download-game-images"
path = "examples/download_game_images.rs"
